/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as LojasRouteImport } from './routes/lojas'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as TrabalheConoscoRouteImport } from './routes/trabalhe-conosco'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminCardapioRouteImport } from './routes/admin/cardapio'
import { Route as AdminChangePasswordRouteImport } from './routes/admin/change-password'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminPedidosRouteImport } from './routes/admin/pedidos'
import { Route as AdminProdutosRouteImport } from './routes/admin/produtos'
import { Route as AdminRelatoriosRouteImport } from './routes/admin/relatorios'
import { Route as AdminVagasRouteImport } from './routes/admin/vagas'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const LojasRoute = LojasRouteImport.update({
  id: '/lojas',
  path: '/lojas',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const TrabalheConoscoRoute = TrabalheConoscoRouteImport.update({
  id: '/trabalhe-conosco',
  path: '/trabalhe-conosco',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCardapioRoute = AdminCardapioRouteImport.update({
  id: '/admin/cardapio',
  path: '/admin/cardapio',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminChangePasswordRoute = AdminChangePasswordRouteImport.update({
  id: '/admin/change-password',
  path: '/admin/change-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/admin/pedidos',
  path: '/admin/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProdutosRoute = AdminProdutosRouteImport.update({
  id: '/admin/produtos',
  path: '/admin/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRelatoriosRoute = AdminRelatoriosRouteImport.update({
  id: '/admin/relatorios',
  path: '/admin/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminVagasRoute = AdminVagasRouteImport.update({
  id: '/admin/vagas',
  path: '/admin/vagas',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/lojas': typeof LojasRoute
  '/menu': typeof MenuRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/vagas': typeof AdminVagasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/lojas': typeof LojasRoute
  '/menu': typeof MenuRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/vagas': typeof AdminVagasRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carrinho': typeof CarrinhoRoute
  '/contato': typeof ContatoRoute
  '/lojas': typeof LojasRoute
  '/menu': typeof MenuRoute
  '/produtos': typeof ProdutosRoute
  '/sobre': typeof SobreRoute
  '/trabalhe-conosco': typeof TrabalheConoscoRoute
  '/admin/cardapio': typeof AdminCardapioRoute
  '/admin/change-password': typeof AdminChangePasswordRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/produtos': typeof AdminProdutosRoute
  '/admin/relatorios': typeof AdminRelatoriosRoute
  '/admin/vagas': typeof AdminVagasRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/carrinho'
    | '/contato'
    | '/lojas'
    | '/menu'
    | '/produtos'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/admin/cardapio'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/vagas'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/carrinho'
    | '/contato'
    | '/lojas'
    | '/menu'
    | '/produtos'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/admin/cardapio'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/vagas'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/carrinho'
    | '/contato'
    | '/lojas'
    | '/menu'
    | '/produtos'
    | '/sobre'
    | '/trabalhe-conosco'
    | '/admin/cardapio'
    | '/admin/change-password'
    | '/admin/login'
    | '/admin/pedidos'
    | '/admin/produtos'
    | '/admin/relatorios'
    | '/admin/vagas'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CarrinhoRoute: typeof CarrinhoRoute
  ContatoRoute: typeof ContatoRoute
  LojasRoute: typeof LojasRoute
  MenuRoute: typeof MenuRoute
  ProdutosRoute: typeof ProdutosRoute
  SobreRoute: typeof SobreRoute
  TrabalheConoscoRoute: typeof TrabalheConoscoRoute
  AdminCardapioRoute: typeof AdminCardapioRoute
  AdminChangePasswordRoute: typeof AdminChangePasswordRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminProdutosRoute: typeof AdminProdutosRoute
  AdminRelatoriosRoute: typeof AdminRelatoriosRoute
  AdminVagasRoute: typeof AdminVagasRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lojas': {
      id: '/lojas'
      path: '/lojas'
      fullPath: '/lojas'
      preLoaderRoute: typeof LojasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trabalhe-conosco': {
      id: '/trabalhe-conosco'
      path: '/trabalhe-conosco'
      fullPath: '/trabalhe-conosco'
      preLoaderRoute: typeof TrabalheConoscoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cardapio': {
      id: '/admin/cardapio'
      path: '/admin/cardapio'
      fullPath: '/admin/cardapio'
      preLoaderRoute: typeof AdminCardapioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/change-password': {
      id: '/admin/change-password'
      path: '/admin/change-password'
      fullPath: '/admin/change-password'
      preLoaderRoute: typeof AdminChangePasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/admin/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/produtos': {
      id: '/admin/produtos'
      path: '/admin/produtos'
      fullPath: '/admin/produtos'
      preLoaderRoute: typeof AdminProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/relatorios': {
      id: '/admin/relatorios'
      path: '/admin/relatorios'
      fullPath: '/admin/relatorios'
      preLoaderRoute: typeof AdminRelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/vagas': {
      id: '/admin/vagas'
      path: '/admin/vagas'
      fullPath: '/admin/vagas'
      preLoaderRoute: typeof AdminVagasRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CarrinhoRoute: CarrinhoRoute,
  ContatoRoute: ContatoRoute,
  LojasRoute: LojasRoute,
  MenuRoute: MenuRoute,
  ProdutosRoute: ProdutosRoute,
  SobreRoute: SobreRoute,
  TrabalheConoscoRoute: TrabalheConoscoRoute,
  AdminCardapioRoute: AdminCardapioRoute,
  AdminChangePasswordRoute: AdminChangePasswordRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminProdutosRoute: AdminProdutosRoute,
  AdminRelatoriosRoute: AdminRelatoriosRoute,
  AdminVagasRoute: AdminVagasRoute,
  AdminIndexRoute: AdminIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
